# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив arr размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  𝑎𝑥+𝑏 так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
import numpy as np
arr = np.random.uniform(0,20,(4,7))
maxx=arr.max()
minn=arr.min()

a=1.0/(maxx-minn)
b=-minn*a
arr_normalized=a*arr+b

print(arr)
print()
print(arr_normalized)

[[ 5.4544056   5.46949986  3.00393624 12.0516551  10.62014489 12.78750011
  14.89203755]
 [ 7.12059568 19.53908738 10.3560764  13.01490485 16.24749226 17.33403148
   9.7535884 ]
 [16.34029393  5.21772517 11.25014054  7.54403914  2.48346015 16.82832851
  12.74280717]
 [ 8.08288597 17.54188371  6.9237114  17.16472545  1.57889636  2.44085156
   4.14054536]]

[[0.2157833  0.21662373 0.07934436 0.58310954 0.50340492 0.62408043
  0.74125833]
 [0.30855459 1.         0.48870193 0.63674203 0.81672828 0.87722536
  0.45515619]
 [0.82189535 0.20260524 0.53848226 0.33213137 0.05036493 0.84906848
  0.62159199]
 [0.36213365 0.88879831 0.29759233 0.86779863 0.         0.04799254
  0.14262927]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль numpy.random) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [3]:
arr2=np.random.randint(0,10,(8,10))
print(arr2)
summ=arr2.sum(axis=1)
ind=np.argmin(summ)
print(f'Индекс - {ind}')
print(f'Строка - {arr2[ind,:]}')

[[5 1 7 9 3 1 5 1 4 1]
 [6 9 3 3 0 1 0 3 3 4]
 [1 3 1 7 9 6 9 5 8 2]
 [0 0 8 9 9 1 5 1 7 1]
 [0 5 2 6 4 7 4 6 4 4]
 [4 3 3 8 1 6 2 5 2 2]
 [1 9 3 3 2 3 1 0 4 8]
 [3 2 8 7 3 6 7 3 8 4]]
Индекс - 1
Строка - [6 9 3 3 0 1 0 3 3 4]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [4]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([6, 7, 8, 9, 10])

eucl_distance = np.linalg.norm(v1 - v2)

print("Евклидово расстояние между векторами:", eucl_distance)

Евклидово расстояние между векторами: 11.180339887498949


4. Решить матричное уравнение A*X*B=-C - найти матрицу X. Где A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]], B=[[3, -1], [2, 1]], C=[[7, 21], [11, 8], [8, 4]]

In [5]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

X = np.dot(np.dot(np.linalg.inv(A), -C), np.linalg.inv(B))
print(X)

[[ 1.00000000e+00  1.11022302e-15]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа 1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки numpy.

1. Файл minutes_n_ingredients.csv содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива numpy типа int32, используя np.loadtxt. Выведите на экран первые 5 строк массива.

In [6]:
recipe=np.loadtxt('minutes_n_ingredients.csv',dtype=np.int32,delimiter=',',skiprows=1)
print(recipe[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [7]:
mean_values = np.mean(recipe[:, 1:], axis=0)
min_values = np.min(recipe[:, 1:], axis=0)
max_values = np.max(recipe[:, 1:], axis=0)
median_values = np.median(recipe[:, 1:], axis=0)
print(mean_values)
print(min_values)
print(max_values)
print(median_values)

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля  𝑞0.75.

In [8]:
q_75 = np.quantile(recipe[:, 1], 0.75, axis=0)
print(q_75)

65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [9]:
zero_duration=np.sum(recipe[:,1]==0)
recipe[:,1][recipe[:,1]==0]=1

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [10]:
unique_rec_count = len(np.unique(recipe[:, 0]))
print(unique_rec_count)

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [11]:
unique_ingr = np.unique(recipe[:, 2])
unique_ingr_count = len(unique_ingr)
print(unique_ingr)
print(unique_ingr_count)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [12]:
recipe_less_5 = recipe[recipe[:, 2] <= 5]
recipe_less_5

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [13]:
ingr_per_minute = recipe[:, 2] / recipe[:, 1]
max_ingr_per_minute = np.max(ingr_per_minute)
print(ingr_per_minute)
print(max_ingr_per_minute)

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [14]:
top100_mean_ingr = np.mean(np.sort(recipe[:, 2])[-100:])
print(top100_mean_ingr)

28.22


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [15]:
random_recipes = recipe[np.random.choice(recipe.shape[0], 10, replace=False)]
print(random_recipes)

[[ 22174     42      9]
 [ 69173     50     10]
 [ 93662     20      5]
 [ 72805     75     13]
 [232248     30      4]
 [101198    143     10]
 [181455     80      9]
 [ 26252     15      5]
 [207281     40     10]
 [500837     25      8]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [16]:
perc_less_than_avg = np.mean(recipe[:, 2] < np.mean(recipe[:, 2])) * 100
print(perc_less_than_avg,'%')

58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [17]:
simple_recipe = np.logical_and(recipe[:, 1] <= 20, recipe[:, 2] <= 5).astype(int)
recipe2 = np.column_stack((recipe, simple_recipe))
print(recipe2)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [18]:
perc_simple_recipes = np.mean(simple_recipe) * 100
print(perc_simple_recipes,'%')

9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [19]:
short_recipes = recipe[recipe[:, 1] < 10]
standard_recipes = recipe[(recipe[:, 1] >= 10) & (recipe[:, 1] < 20)]
long_recipes = recipe[recipe[:, 1] >= 20]

max_count = min(len(short_recipes), len(standard_recipes), len(long_recipes))
result_array = np.zeros((3, max_count, 3))
result_array[0, :len(short_recipes), :] = short_recipes[:max_count]
result_array[1, :len(standard_recipes), :] = standard_recipes[:max_count]
result_array[2, :len(long_recipes), :] = long_recipes[:max_count]

print(result_array.shape)

(3, 7588, 3)
