# Введение в обработку текста на естественном языке

## Задачи для совместного разбора

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import pymorphy2

1. Считайте слова из файла `litw-win.txt` и запишите их в список `words`. В заданном предложении исправьте все опечатки, заменив слова с опечатками на ближайшие (в смысле расстояния Левенштейна) к ним слова из списка `words`. Считайте, что в слове есть опечатка, если данное слово не содержится в списке `words`. 

In [3]:
pip install python-Levenshtein

  Obtaining dependency information for python-Levenshtein from https://files.pythonhosted.org/packages/72/8e/559c539e76bc0b1defec3da39a047fe151258efc9b215bf41db41e2c7922/python_Levenshtein-0.25.1-py3-none-any.whl.metadata
  Obtaining dependency information for Levenshtein==0.25.1 from https://files.pythonhosted.org/packages/47/19/4528246e25bb79fa8d4adae6640251c613f05eb310d79307d1ac53c7bf28/Levenshtein-0.25.1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for rapidfuzz<4.0.0,>=3.8.0 from https://files.pythonhosted.org/packages/04/10/2c0ef45d4ace8dde87cfb91e48fb5c9976f8e01a57eb3230d90b82801dc5/rapidfuzz-3.9.3-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/98.4 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/98.4 kB ? eta -:--:--
   ------------------------ --------------- 61.4/98.4 kB 656.4 kB/s eta 0:00:01
   ---------------------------------------- 98.4/98.4 kB 801.1 kB/s eta 0:00:00
   -----------------------

In [4]:
text = '''с велИчайшим усилеем выбравшись из потока убегающих людей Кутузов со свитой уменьшевшейся вдвое поехал на звуки выстрелов русских орудий'''

In [37]:
import Levenshtein

# cчитываем слова из файла
with open("data\litw-win.txt", "r") as f:
    words = [line.split()[1] for line in f]

    
# исправление опечаток
def correct_word(word, words):
    if word in words:  # если слово в words, значит исправлять не надо, просто возвращаем слово
        return word
    else:
        # находим ближайшее слово по расстоянию Левенштейна
        min_distance = float('inf')
        corrected_word = None
        for w in words:
            distance = Levenshtein.distance(word, w)
            if distance < min_distance:
                min_distance = distance
                corrected_word = w
        return corrected_word

corrected_sentence = " ".join([correct_word(word, words) for word in text.split()])

print(corrected_sentence)

читайте слова из файл и и запишите их в список и и заданной предложении исправьте все опечатки заменив слова с печатками на ближайшие в смысле расстояния рубинштейна к ним слова из списка и читайте что в слове есть опечатки если данное слово не содержится в списке и


2. Разбейте текст из формулировки задания 1 на слова; проведите стемминг и лемматизацию слов.

стемминг удаляет суффиксы и префиксы из слов

лемматизация приводит слова к их основной форме.

In [8]:
#Разбиение текста на слова:
import nltk

words = nltk.word_tokenize(corrected_sentence)
print(words)

['с', 'величайшим', 'усилием', 'выбравшись', 'из', 'потока', 'убегающих', 'людей', 'кутузов', 'со', 'свитой', 'уменьшившейся', 'вдвое', 'поехал', 'на', 'звуки', 'выстрелов', 'русских', 'орудий']


3. Преобразуйте предложения из формулировки задания 1 в векторы при помощи `CountVectorizer`.

In [16]:
text = 'Считайте слова из файла litw-win.txt и запишите их в список words. В заданном предложении исправьте все опечатки, заменив слова с опечатками на ближайшие (в смысле расстояния Левенштейна) к ним слова из списка words. Считайте, что в слове есть опечатка, если данное слово не содержится в списке words.'

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import sent_tokenize

# Токенизировать текст на предложения на русском языке
texti = sent_tokenize(text, language="russian")

# Создать корпус из токенизированных предложений
corpus = [i for i in texti]

# Создать экземпляр CountVectorizer
vectorizer1 = CountVectorizer()

# Создать экземпляр CountVectorizer с анализатором уровня слова и диапазоном n-грамм (2, 2)
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

# Преобразовать корпус в матрицу признаков с помощью CountVectorizer
X = vectorizer1.fit_transform(corpus)

# Получить имена признаков из CountVectorizer
vectorizer1.get_feature_names_out()

# Вывести матрицу признаков
print(X.toarray())
print(" ")

# Преобразовать корпус в матрицу признаков с помощью CountVectorizer
X = vectorizer2.fit_transform(corpus)

# Получить имена признаков из CountVectorizer
vectorizer2.get_feature_names_out()

# Вывести матрицу признаков
print(X.toarray())

[[1 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0]
 [0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 1 1 0 1 0 1 1 1 1 2 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1]]
 
[[1 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1
  0]
 [0 0 0 1 1 0 0 0 1 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 1 0 0 1 0 1 0 0 0 0 0
  0]
 [0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1 0
  1]]


## Лабораторная работа 9

### Расстояние редактирования

1.1 Загрузите предобработанные описания рецептов из файла `preprocessed_descriptions.csv`. Получите набор уникальных слов `words`, содержащихся в текстах описаний рецептов (воспользуйтесь `word_tokenize` из `nltk`). 

In [ ]:
нету preprocessed_descriptions.csv

1.2 Сгенерируйте 5 пар случайно выбранных слов и посчитайте между ними расстояние редактирования.

In [32]:
import random
import Levenshtein

# Сгенерировать 5 пар случайных слов
pairs = [(random.choice(words), random.choice(words)) for i in range(5)]

# Посчитать расстояние редактирования для каждой пары
distances = [Levenshtein.distance(pair[0], pair[1]) for pair in pairs]

# Вывести пары слов и расстояния редактирования
for pair, distance in zip(pairs, distances):
    print(f"{pair[0]} -> {pair[1]}: {distance}")

пар -> между: 5
Сгенерируйте -> пар: 11
редактирования -> посчитайте: 12
и -> выбранных: 9
расстояние -> ними: 9


1.3 Напишите функцию, которая для заданного слова `word` возвращает `k` ближайших к нему слов из списка `words` (близость слов измеряется с помощью расстояния Левенштейна)

In [42]:
import Levenshtein

def find_k_nearest_neighbors(word, words, k):
    # Посчитать расстояния Левенштейна между заданным словом и всеми словами из списка
    distances = [Levenshtein.distance(word, w) for w in words]

    # Отсортировать слова по расстоянию Левенштейна
    sorted_words = sorted(zip(distances, words), key=lambda x: x[0])

    # Вернуть k ближайших соседей
    return [w for d, w in sorted_words[:k]]

find_k_nearest_neighbors('солнце', words, 10)

['солнце',
 'солнц',
 'солне',
 'сонце',
 'солнца',
 'солнцу',
 'солнцы',
 'солнцем',
 'соне',
 'солн']

### Стемминг, лемматизация

2.1 На основе результатов 1.1 создайте `pd.DataFrame` со столбцами: 
    * word
    * stemmed_word 
    * normalized_word 

Столбец `word` укажите в качестве индекса. 

Для стемминга воспользуйтесь `SnowballStemmer`, для нормализации слов - `WordNetLemmatizer`. Сравните результаты стемминга и лемматизации.

2.2. Удалите стоп-слова из описаний рецептов. Какую долю об общего количества слов составляли стоп-слова? Сравните топ-10 самых часто употребляемых слов до и после удаления стоп-слов.

### Векторное представление текста

3.1 Выберите случайным образом 5 рецептов из набора данных. Представьте описание каждого рецепта в виде числового вектора при помощи `TfidfVectorizer`

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

# Загрузка данных из файла
file_path = 'Пока нет файла. Увы'
df = pd.read_csv(file_path)

# Выбор случайных 5 рецептов
random_recipes = df.sample(n=5, random_state=42)

# Инициализация векторизатора TF-IDF
vectorizer = TfidfVectorizer()

# Векторизация описаний выбранных рецептов
tfidf_matrix = vectorizer.fit_transform(random_recipes['description'])

# Преобразование в DataFrame для удобства
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), index=random_recipes['title'], columns=vectorizer.get_feature_names_out())

tfidf_df


3.2 Вычислите близость между каждой парой рецептов, выбранных в задании 3.1, используя косинусное расстояние (`scipy.spatial.distance.cosine`) Результаты оформите в виде таблицы `pd.DataFrame`. В качестве названий строк и столбцов используйте названия рецептов.

In [ ]:
from scipy.spatial.distance import cosine

# Вычисление косинусного расстояния и создание таблицы
cosine_distances = pd.DataFrame(index=random_recipes['title'], columns=random_recipes['title'])

for i, title1 in enumerate(random_recipes['title']):
    for j, title2 in enumerate(random_recipes['title']):
        if i != j:
            cosine_distances.at[title1, title2] = cosine(tfidf_df.loc[title1], tfidf_df.loc[title2])
        else:
            cosine_distances.at[title1, title2] = 0.0

cosine_distances

3.3 Какие рецепты являются наиболее похожими? Прокомментируйте результат (словами).

In [ ]:
# Поиск пары рецептов с минимальным косинусным расстоянием (кроме диагонали)
min_distance = float('inf')
min_pair = None

for i, title1 in enumerate(random_recipes['title']):
    for j, title2 in enumerate(random_recipes['title']):
        if i != j and cosine_distances.at[title1, title2] < min_distance:
            min_distance = cosine_distances.at[title1, title2]
            min_pair = (title1, title2)

min_distance, min_pair